py_library(
    name = "adapter_lib",
    srcs = ["adapter_lib.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "adapter_test",
    srcs = ["adapter_test.py"],
    deps = [":adapter_lib"],
)
