py_library(
    name = "singleton_lib",
    srcs = ["singleton_lib.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "singleton_test",
    srcs = ["singleton_test.py"],
    deps = [":singleton_lib"],
)
