py_library(
    name = "factory_lib",
    srcs = ["factory_lib.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "factory_test",
    srcs = ["factory_test.py"],
    deps = [":factory_lib"],
)
